### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by divyanshu13** [tyiannak/pyAudioAnalysis#127]
Getting the following error when trying to execute using command prompt

C:\Users\divyanshu.kumar\Documents\GitHub\pyAudioAnalysis>python audioAnalysis.py
  File "audioAnalysis.py", line 47
    print "Beat: {0:d} bpm ".format(int(BPM))
                           ^
SyntaxError: invalid syntax

**Comment by jhoelzl** [comment]
Seems that you are using Python3 where the brackets have to be applied for the "print" command. Since there are several pull requests, the author of this repo has not decided to make this library Python 3 compatible.

However, you fix all print commands in the code on your own, then it should work. Or have a look at the code of some open pull requests...

**Comment by divyanshu13** [comment]
Thanks, for the clarification.
