### ISSUE TITLE
Memory leak in stFeatureExtraction

### ISSUE THREAD

**Issue by stevenwff** [tyiannak/pyAudioAnalysis#173]
I tried to build a audio processing server, but I found a memory leak issue when I use [audioFeatureExtraction.stFeatureExtraction]. Then I wrote a test script as following(run with Python 2.7):

from pyAudioAnalysis import audioBasicIO
from pyAudioAnalysis import audioFeatureExtraction
audio_file = "sample_origin.wav"
[fs, data] = audioBasicIO.readAudioFile(audio_file)
while True:
    features = audioFeatureExtraction.stFeatureExtraction(data, fs, 960, 960)

With the Windows task manager, I found the memory it used keep increasing, from 200MB to 270MB within 20 minutes. I tested my script both on Windows 10  and Ubuntu 16.04, and it seemed the same result.

Anyone has come across this problem? I wish to make sure it's a bug or not.
Looking forward to responses.

**Comment by pvanlaar** [comment]
I am not sure about the cause, but I have encountered long feature extraction times as well. I suspect it is due to windowing issues. I found the following comment in one of the functions.

`def stChromaFeatures(X, fs, nChroma, nFreqsPerChroma):`
`    #TODO: 1 complexity`
`    #TODO: 2 bug with large windows`

I will investigate this in more depth
