### ISSUE TITLE
What method is there to solve the problem?

### ISSUE THREAD

**Issue by thaingiW** [tyiannak/pyAudioAnalysis#180]
Writing berlin data set to file...
Traceback (most recent call last):
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master/find_best_model.py", line 163, in <module>
    functions.feature_extract(ds.data, nb_samples=len(ds.targets), dataset=dataset)
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master/utility/functions.py", line 20, in feature_extract
    hr_pitch = audioFeatureExtraction.stFeatureSpeed(x, Fs, globalvars.frame_size * Fs, globalvars.step * Fs)
  File "/usr/local/lib/python3.5/dist-packages/pyAudioAnalysis/audioFeatureExtraction.py", line 669, in stFeatureSpeed
    [fbank, freqs] = mfccInitFilterBanks(Fs, nfft, lowfreq, linsc, logsc, nlinfil, nlogfil)
TypeError: mfccInitFilterBanks() takes 2 positional arguments but 7 were given

**Comment by pvanlaar** [comment]
Could you provide a more clear issue next time please, instead of this traceback dump? Create a minimal example when the error occurs. And provide the code which triggers the error. That makes the error reproducible. Furthermore you could also make an effort yourself to debug this one yourself and create a real issue instead of a puzzle.

## The issue
In the function `stFeatureSpeed` from audioFeatureExtraction.py make a call: `[fbank, freqs] = mfccInitFilterBanks(Fs, nfft, lowfreq, linsc, logsc, nlinfil, nlogfil)`, but this function is only able to receive two arguments. It has the following signature: `def mfccInitFilterBanks(fs, nfft)`

The "extra" arguments are: lowfreq, linsc, logsc, nlinfil, nlogfil

These are all defined in the mfccInitFilterBanks function itself wit exactly the same values. 

Note that there is a comment in the source code (audioFeatureExtraction.py) that says that the `stFeatureSpeed()` function is work in progress. so there could be many (non obvious) bugs. apart from this one.

## Solutions
### Quick fix
Simply remove the arguments from the call in the `stFeatureSpeed` function.

### Default arguments
Alter the `mfccInitFilterBanks` function to receive these parameters, but with defaults set. I will create a pull request with this solution.

**Comment by thaingiW** [comment]
Thank you!
