### ISSUE TITLE
Non-music detection training fails

### ISSUE THREAD

**Issue by TomJL** [tyiannak/pyAudioAnalysis#20]
I'm trying to make a classifier with pyAudioAnalysis to detect non-music sections of songs. When I set everything up and run it, the trainer blows through every step in about 5 seconds total. It neither learns, nor changes with different parameters. If 40% of the data is music, it gets 40% wrong. It simply chooses to predict either music or non-music for every piece of data. Any insight into what might cause this?

**Comment by ar0ck** [comment]
have you tried turning it off then on again

**Comment by tyiannak** [comment]
Please provide some more info: are you trying to train your own binary classifier (music vs non-music)? 
Also, what do you mean "It simply chooses to predict either music or non-music for every piece of data.". It seems that you are trying to classify the whole audio file. If i get it correctly, what you need to do is segmentation/classification not classification alone. If this is the case, check the segmentation wiki page for instructions.

**Comment by TomJL** [comment]
I was trying to train a classifier using aT.featureAndTrain to detect music vs non-music. I cut up a bunch of music files (that I listened to and classified myself) to segments that were about 15-20 seconds of either music or non-music, and I put them in their respectively named folders. When I ran them through featureAndTrain, it finished really quickly. When I then tried to use the models it output, it would only classify things as non-music. I retrained it with equal amounts of files in both folders, but that time the classification of choice was music. The point is, it would pick either music or non-music during the training period, and then only classify files as that when used afterwards.

**Comment by TomJL** [comment]
(this result happened when I used fileClassification and segmentation for evalutation)

**Comment by tyiannak** [comment]
How many segments have u used for training? Seems like the SVM overfitted which happens if you provide very few samples.

**Comment by tianqig** [comment]
Any guideline as to how many training samples are needed to achieve good classification performance ? 

I tried to classify three types of sounds: breaking glass, vacuum cleaner, water bubble, very distinctive sound tracks. For each type I have 2 samples, around 5-10 second/sample. When calling
aT.featureAndTrain(subdirectories, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "svm", "svmModel", False), it was running fine, but classification failed totally: the output was:
=========================
Confusion Matrix:
	bre 	        bub 	vac
bre 	11.11 	11.11 	11.11
bub 11.11 	11.11 	11.11
vac 	11.11 	11.11 	11.11
Selected params: 0.00100
==========================
so it could not classify these thee classes at all. Wonder if this was caused by too few training samples, or other problems?

Thanks
