### ISSUE TITLE
stFeatureExtraction() ValueError

### ISSUE THREAD

**Issue by mccoya2** [tyiannak/pyAudioAnalysis#33]
Thanks for this effort. It really looks promising.

The following code:

[Fs, x] = audioBasicIO.readAudioFile('myWavFile.wav')
F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050_Fs, 0.025_Fs)

results in the following error:

_**'File "/Users/anthony.mccoy/anaconda/lib/python2.7/site-packages/pyAudioAnalysis/audioFeatureExtraction.py", line 48, in stEnergyEntropy
subWindows = frame.reshape(subWinLength, numOfShortBlocks, order='F').copy()'

ValueError: total size of new array must be unchanged**_

**Comment by anastasiaTesla** [comment]
Hi mccoya2, 
because I came across this problem many times, I think the error is being produced because x is stereophonic and in order stFeatureExtraction to work, you must specify a one dimensional signal. So for example, try  F = audioFeatureExtraction.stFeatureExtraction(x[:,0], Fs, 0.050Fs, 0.025Fs)
or you can use the stereo2mono function from the audioBasicIO module, to convert your wav file into monophonic.

**Comment by mccoya2** [comment]
Hi anastasiaTesla,

Thank you very much for your quick reply. Your spot on! Your suggestion has solved the issue. 

Maybe a future version could detect whether or not the signal is stereophonic and deal with it accordingly.

Thanks again.
